name: Cairo tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "**.md"
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "**.md"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - uses: actions/checkout@v3

      - name: Debug NODE_URL
        run: |
          if [ -n "$NODE_URL" ]; then
            echo "NODE_URL is set (value hidden)"
          else
            echo "NODE_URL is NOT set or is empty"
          fi

      - uses: software-mansion/setup-scarb@v1
      - run: scarb fmt --check
      - run: scarb build

      - uses: foundry-rs/setup-snfoundry@v3
      - run: snforge test
